version: "3.9"

services:
  tg-bot:
    build:
      context: ../../apps/tg-bot
      dockerfile: Dockerfile
    container_name: skazka-tg-bot
    env_file:
      - ./.env
    restart: unless-stopped
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: skazka-postgres
    environment:
      POSTGRES_DB: skazka
      POSTGRES_USER: skazka
      POSTGRES_PASSWORD: skazka
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pg_data:
